- name: Return motd to registered var
  command: hostname
  register: our_hostname_command

- debug:
    msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

- debug:
    msg: "Output of our hostname command is: {{ our_hostname_command.stdout }}"

- debug:
    msg: Hello World

- name: Install the latest version of Apache
  yum:
    name: httpd
    state: latest