- debug:
    msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

- name: Install the latest version of Apache
  become: yes  
  become_user: root
  yum:
    name: httpd
    state: latest