-
  name: Stop Firewall
  become: yes
  become_user: root
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Verify the key, using a fingerprint, before import
  ansible.builtin.rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    fingerprint: EBC6 E12C 62B1 C734 026B  2122 A20E 5214 6B8D 79E6

- name: Add repository
  yum_repository:
    name: Elastic
    description: Elastic YUM repo
    baseurl: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.1-x86_64.rpm

- name: Run a command as the root user
  command: sudo yum install --enablerepo=elasticsearch elasticsearch
  become: true
  become_user: root
