-
  name: Stop Firewall
  become: yes
  become_user: root
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Verify the key, using a fingerprint, before import
  ansible.builtin.rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    fingerprint: EBC6 E12C 62B1 C734 026B  2122 A20E 5214 6B8D 79E6

-
  name: creating repo
  yum_repository:
    name: elastic-7.x
    description: Elastic repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
  become: true
  become_user: root
    #autorefresh=1? https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_repository_module.html
    #type=rpm-md?



# [elastic-7.x]
# name=Elastic repository for 7.x packages
# baseurl=https://artifacts.elastic.co/packages/7.x/yum
# gpgcheck=1
# gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
# enabled=1
# autorefresh=1
# type=rpm-md

- name: Install the latest version of Filebeat
  yum:
    name: filebeat
    state: latest
  become: true
  become_user: root

- name: Template a file to /etc/file.conf
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0600'
  become: true
  become_user: root

- name: Enable Module
  command: filebeat modules enable system
  become: true
  become_user: root

- name: Setup Assets
  command: filebeat setup -e
  become: true
  become_user: root
  run_once: true

- name: Restart Filbeat
  systemd:
    name: filebeat
    state: restarted
    enabled: yes
  become: true
  become_user: root

- name: All Done
  debug:
    msg: ALL DONE "http://{{elasticsearch_host}}:5601/app/home#/"