-
  name: Install the latest version of Apache
  become: yes
  become_user: root
  yum:
    name: httpd
    state: latest

-
  name: Make sure a service unit is running
  become: yes
  become_user: root
  systemd:
    state: started
    name: httpd
    enabled: yes

-
  name: Stop Firewall
  become: yes
  become_user: root
  systemd:
    name: firewalld
    state: stopped
    enabled: no
