-
  name: Stop Firewall
  become: yes
  become_user: root
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Verify the key, using a fingerprint, before import
  ansible.builtin.rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    fingerprint: EBC6 E12C 62B1 C734 026B  2122 A20E 5214 6B8D 79E6

- name: Add repository
  shell:
  [elasticsearch]
name=Elasticsearch repository for 7.x packages
baseurl=https://artifacts.elastic.co/packages/7.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=0
autorefresh=1
type=rpm-md

- name: Run a command as the root user
  command: sudo yum install --enablerepo=elasticsearch elasticsearch
  become: true
  become_user: root
